# Generated by Django 2.2.5 on 2019-09-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remind_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reminde', models.CharField(max_length=100)),
                ('time_field', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_visit', models.CharField(max_length=100)),
                ('date_of_visit', models.DateField()),
                ('time_to_remind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Remind_field')),
            ],
        ),
    ]
