# Generated by Django 2.2.5 on 2019-09-29 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time_to_remind',
            field=models.TimeField(choices=[(datetime.time(1, 0), 'За час'), (datetime.time(2, 0), 'За 2 часа'), (datetime.time(4, 0), 'За 4 часа')]),
        ),
        migrations.DeleteModel(
            name='Remind_field',
        ),
    ]
