# Generated by Django 2.2.5 on 2019-09-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20190929_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='date_of_ring_for_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date_of_visit',
            field=models.DateTimeField(),
        ),
    ]
